### ISSUE TITLE
Pre-release checklist for 0.8.0

### ISSUE THREAD

**Issue by gary-rowe** [gary-rowe/hid4java#147]
Here's what's outstanding before 0.8.0 can be released.

**Pre-release checklist**

- [x] FIDO2 device verified working in all test environments
- [x] `develop-SNAPSHOT` deployed to Maven Central (snapshots)
- [x] Issues for release marked as "Awaiting merge"

Feedback received from community verifying the following libraries for `develop-SNAPSHOT`:

- [x] `darwin-x86-64` - macOS 64-bit
- [x] `darwin-aarch64` - macOS ARM64
- [x] `linux-aarch64` - Linux ARMv8 64-bit only
- [x] `linux-amd64` - Linux AMD 64-bit only
- [x] `linux-arm` - Linux ARMv7 hard float 32-bit only
- [x] `linux-armel` - Linux ARMv5 soft float 32-bit
- [x] `linux-riscv64` - Linux RISC-V 64-bit
- [x] `linux-x86-64` - Linux x86 64-bit only
- [x] `linux-x86` - Linux x86 32-bit only
- [x] `win32-x86` - Windows 32-bit only
- [x] `win32-x86-64` - Windows 64-bit only
- [x] `win32-aarch64` - Windows 64-bit ARM64
